# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-01 07:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20170601_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=models.CharField(max_length=20000),
        ),
    ]
