# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-01 07:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20170601_1242'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_title',
            field=models.CharField(default=b'', max_length=200),
        ),
    ]
