# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-01 07:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_remove_question_question_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='question_text',
            new_name='post_text',
        ),
    ]
